-- Phase 3.9.5: Production hardening — feature flags + command enum alignment

ALTER TABLE "V3FeatureFlag" ADD COLUMN IF NOT EXISTS "holdEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "V3FeatureFlag" ADD COLUMN IF NOT EXISTS "conferenceEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "V3FeatureFlag" ADD COLUMN IF NOT EXISTS "queueEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "V3FeatureFlag" ADD COLUMN IF NOT EXISTS "ivrEnabled" BOOLEAN NOT NULL DEFAULT false;

-- Extend V3CommandType enum (additive; each value in separate statement for PG compatibility)
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'HOLD';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'UNHOLD';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'TRANSFER';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'GATHER';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'ENQUEUE';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'DEQUEUE';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'CREATE_CONFERENCE';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'ADD_PARTICIPANT';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'REMOVE_PARTICIPANT';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'MUTE_PARTICIPANT';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'UNMUTE_PARTICIPANT';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'DESTROY_CONFERENCE';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'PLAY_GREETING';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'START_VOICEMAIL';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'STOP_VOICEMAIL';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'START_RECORDING';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'STOP_RECORDING';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'REJECT';
ALTER TYPE "V3CommandType" ADD VALUE IF NOT EXISTS 'FORWARD';

-- Outbox retention / claim tuning
CREATE INDEX IF NOT EXISTS "V3CommandOutbox_status_updatedAt_idx"
  ON "V3CommandOutbox"("status", "updatedAt");

CREATE INDEX IF NOT EXISTS "V3CallSession_endedAt_idx"
  ON "V3CallSession"("endedAt");
