/** Conference shared constants (Phase 3.7). */

const CONFERENCE_ACTION = {
  CREATE: 'CREATE',
  JOIN: 'JOIN',
  LEAVE: 'LEAVE',
  REMOVE: 'REMOVE',
  MERGE: 'MERGE',
  DESTROY: 'DESTROY',
  MUTE: 'MUTE',
  UNMUTE: 'UNMUTE',
  START_RECORDING: 'START_RECORDING',
  STOP_RECORDING: 'STOP_RECORDING',
  CLEANUP: 'CLEANUP',
};

const CONFERENCE_STATUS = {
  CREATED: 'CREATED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

const PARTICIPANT_ROLE = {
  HOST: 'HOST',
  PARTICIPANT: 'PARTICIPANT',
};

const POLICY_ACTION = {
  ALLOW: 'ALLOW',
  DENY: 'DENY',
};

const CONFERENCE_RECORDING_POLICY = {
  ALWAYS: 'ALWAYS',
  ON_DEMAND: 'ON_DEMAND',
  DISABLED: 'DISABLED',
};

const DEFAULT_LIMITS = {
  maxParticipants: 10,
  conferenceTimeoutSec: 3600,
  hostRequired: true,
  conferenceRecordingPolicy: CONFERENCE_RECORDING_POLICY.ON_DEMAND,
};

module.exports = {
  CONFERENCE_ACTION,
  CONFERENCE_STATUS,
  PARTICIPANT_ROLE,
  POLICY_ACTION,
  CONFERENCE_RECORDING_POLICY,
  DEFAULT_LIMITS,
};
