export const endpoints = {
  auth: {
    login: '/api/auth/login',
    refresh: '/api/auth/refresh',
    me: '/api/auth/me',
    logout: '/api/auth/logout',
  },
  dashboard: {
    stats: '/api/dashboard/stats',
  },
  calls: {
    list: (limit = 50) => `/api/calls?limit=${limit}`,
  },
  tenant: {
    profile: '/api/tenant/profile',
    extensions: '/api/tenant/extensions',
    extension: (id: string) => `/api/tenant/extensions/${id}`,
  },
  softphone: {
    internalCall: '/api/softphone/internal-call',
    token: '/api/softphone/token',
    config: '/api/softphone/config',
    presence: '/api/softphone/presence',
    callAccepted: '/api/softphone/call-accepted',
    callLog: '/api/softphone/call-log',
    pushToken: '/api/softphone/push-token',
    devices: '/api/softphone/devices',
    device: (deviceId: string) => `/api/softphone/devices/${deviceId}`,
    diagnostics: '/api/softphone/diagnostics',
    telemetry: '/api/softphone/telemetry',
  },
  messaging: {
    conversations: '/api/conversations',
    conversationMessages: (id: string) => `/api/conversations/${id}/messages`,
    markRead: (id: string) => `/api/conversations/${id}/read`,
    send: '/api/messages/send',
    attachments: '/api/messages/attachments',
    smsConfig: '/api/sms/config',
  },
  voicemail: {
    list: (limit = 50) => `/api/tenant/voicemails?limit=${limit}`,
    markRead: (id: string) => `/api/tenant/voicemails/${id}/read`,
    stream: (id: string) => `/api/tenant/voicemails/${id}/stream`,
  },
  ai: {
    voicemailSummary: (id: string) => `/api/ai/summaries/voicemail/${id}`,
    generateVoicemailSummary: (id: string) => `/api/ai/summaries/voicemail/${id}/generate`,
    callSummary: (id: string) => `/api/ai/summaries/call/${id}`,
    generateCallSummary: (id: string) => `/api/ai/summaries/call/${id}/generate`,
    conversationSummary: (id: string) => `/api/ai/summaries/conversation/${id}`,
    generateConversationSummary: (id: string) => `/api/ai/summaries/conversation/${id}/generate`,
    voicemailTranscript: (id: string) => `/api/ai/transcripts/voicemail/${id}`,
    generateVoicemailTranscript: (id: string) => `/api/ai/transcripts/voicemail/${id}/generate`,
    callTranscript: (id: string) => `/api/ai/transcripts/call/${id}`,
    generateCallTranscript: (id: string) => `/api/ai/transcripts/call/${id}/generate`,
    assistantSuggestions: '/api/ai/assistant/suggestions',
    assistantQuery: '/api/ai/assistant/query',
    assistantStream: '/api/ai/assistant/stream',
  },
} as const;
