/** @typedef {'PENDING'|'SENT'|'ACKED'|'FAILED'|'DEAD'} V3OutboxStatus */

const ENGINE_VERSION = 1;

const STREAM = {
  INGRESS: 'v3:stream:telephony-ingress',
  DLQ: 'v3:stream:telephony-dlq',
  CONSUMER_GROUP: 'v3-workers',
};

const REDIS = {
  SESSION_PREFIX: 'v3:session:',
  LEG_PREFIX: 'v3:leg:',
  LOCK_PREFIX: 'v3:lock:session:',
  TIMER_PREFIX: 'v3:timer:',
  FLAG_PREFIX: 'v3:flags:',
  HEARTBEAT_PREFIX: 'v3:worker:heartbeat:',
  HEARTBEAT_INDEX: 'v3:worker:heartbeat:index',
  INGRESS_PAYLOAD_PREFIX: 'v3:ingress:payload:',
  SIP_PREFIX: 'v3:sip:',
  ACTIVE_PREFIX: 'v3:active:tenant:',
};

const TTL = {
  SESSION_SEC: 3600,
  SESSION_BUFFER_SEC: 900,
  DEDUP_SEC: 86400,
  LOCK_SEC: 30,
  FLAG_SEC: 300,
  HEARTBEAT_SEC: 30,
  SIP_CACHE_SEC: 900,
  TIMER_MIN_SEC: 1,
};

const OUTBOX = {
  DEFAULT_MAX_ATTEMPTS: 5,
  BASE_RETRY_MS: 500,
  MAX_RETRY_MS: 60000,
  POLL_BATCH: 50,
  CLAIM_LEASE_SEC: 30,
};

const WORKER = {
  DEFAULT_BLOCK_MS: 5000,
  DEFAULT_COUNT: 10,
  MAX_DELIVERY_ATTEMPTS: 5,
  STALE_CLAIM_MS: 60000,
  SHUTDOWN_DRAIN_MS: 30000,
  SHUTDOWN_BLOCK_MS: 500,
};

const HEALTH = {
  QUEUE_LAG_MAX_MS: Number(process.env.V3_QUEUE_LAG_MAX_MS) || 60000,
  QUEUE_DEPTH_MAX: Number(process.env.V3_QUEUE_DEPTH_MAX) || 10000,
  DLQ_DEPTH_MAX: Number(process.env.V3_DLQ_DEPTH_MAX) || 1000,
  OUTBOX_DEAD_MAX: Number(process.env.V3_OUTBOX_DEAD_MAX) || 100,
  OUTBOX_PROCESSING_STALE_SEC: Number(process.env.V3_OUTBOX_PROCESSING_STALE_SEC) || 120,
};

const RETENTION = {
  PROCESSED_EVENT_DAYS: Number(process.env.V3_PROCESSED_EVENT_RETENTION_DAYS) || 30,
  INGRESS_PAYLOAD_SEC: Number(process.env.V3_INGRESS_PAYLOAD_TTL_SEC) || 86400,
  OUTBOX_ACKED_DAYS: Number(process.env.V3_OUTBOX_ACKED_RETENTION_DAYS) || 7,
  OUTBOX_DEAD_DAYS: Number(process.env.V3_OUTBOX_DEAD_RETENTION_DAYS) || 30,
};

const EXECUTOR = {
  LEASE_RENEW_INTERVAL_MS: Number(process.env.V3_EXECUTOR_LEASE_RENEW_MS) || 10000,
};

const METRICS = {
  HISTOGRAM_MAX_SAMPLES: 1000,
  REDIS_PREFIX: 'v3:metrics:',
};

const GLOBAL_FLAGS = {
  TELEPHONY_V3_GLOBAL: 'TELEPHONY_V3_GLOBAL',
  TELEPHONY_V3_INGRESS_ENABLED: 'TELEPHONY_V3_INGRESS_ENABLED',
  TELEPHONY_V3_OUTBOX_PAUSED: 'TELEPHONY_V3_OUTBOX_PAUSED',
  TELEPHONY_V3_CALLMANAGER_ENABLED: 'TELEPHONY_V3_CALLMANAGER_ENABLED',
  TELEPHONY_V3_EXECUTOR_ENABLED: 'TELEPHONY_V3_EXECUTOR_ENABLED',
};

const CALLMANAGER = {
  OPTIMISTIC_LOCK_MAX_RETRIES: 3,
  LOCK_RETRIES: 5,
};

module.exports = {
  ENGINE_VERSION,
  STREAM,
  REDIS,
  TTL,
  OUTBOX,
  WORKER,
  HEALTH,
  RETENTION,
  EXECUTOR,
  METRICS,
  GLOBAL_FLAGS,
  CALLMANAGER,
};
