/**
 * VSP Phone V3 — Phase 2 CallManager foundation entry point.
 */

const { handleV3WebhookIngress, isIngressEnabled } = require('./WebhookGateway/gateway');
const { getV3ReadinessStatus } = require('./Health/healthService');
const { metrics } = require('./Utils/metrics');
const { ENGINE_VERSION } = require('./constants');

module.exports = {
  ENGINE_VERSION,
  handleV3WebhookIngress,
  isIngressEnabled,
  getV3ReadinessStatus,
  metrics,
  WebhookGateway: require('./WebhookGateway/gateway'),
  normalize: require('./WebhookGateway/normalize'),
  streams: require('./Redis/streams'),
  locks: require('./Redis/locks'),
  sessionCache: require('./Redis/sessionCache'),
  legCache: require('./Redis/legCache'),
  commandOutbox: require('./Outbox/commandOutbox'),
  featureFlags: require('./FeatureFlags/featureFlagService'),
  timerService: require('./Timer/timerService'),
  sessionRepository: require('./Session/sessionRepository'),
  ingressWorker: require('./Workers/ingressWorker'),
  ingressDispatcher: require('./Workers/ingressDispatcher'),
  callManager: require('./CallManager/callManager'),
  sessionManager: require('./Sessions/sessionManager'),
  legManager: require('./Sessions/legManager'),
  callPersistence: require('./Sessions/callPersistence'),
  stateMachine: require('./StateMachine/stateMachine'),
  domainEventBus: require('./Events/domainEventBus'),
  commandBus: require('./Commands/commandBus'),
  policyEngine: require('./Policy/policyEngine'),
  commandExecutor: require('./Executor/commandExecutor'),
  telnyxAdapter: require('./Executor/telnyxAdapter'),
  failureClassifier: require('./Executor/failureClassifier'),
  deskRouter: require('./Routing/deskRouter'),
  deskResolver: require('./Routing/deskResolver'),
  deskPolicy: require('./Routing/deskPolicy'),
  deskCommandBuilder: require('./Routing/deskCommandBuilder'),
  deskRouteResult: require('./Routing/deskRouteResult'),
  mobileRouter: require('./Routing/mobileRouter'),
  mobileResolver: require('./Routing/mobileResolver'),
  mobilePolicy: require('./Routing/mobilePolicy'),
  mobileCommandBuilder: require('./Routing/mobileCommandBuilder'),
  mobileRouteResult: require('./Routing/mobileRouteResult'),
  pstnRouter: require('./Routing/pstnRouter'),
  pstnResolver: require('./Routing/pstnResolver'),
  pstnPolicy: require('./Routing/pstnPolicy'),
  pstnCommandBuilder: require('./Routing/pstnCommandBuilder'),
  pstnRouteResult: require('./Routing/pstnRouteResult'),
  holdManager: require('./HoldTransfer/holdManager'),
  transferManager: require('./HoldTransfer/transferManager'),
  holdPolicy: require('./HoldTransfer/holdPolicy'),
  transferPolicy: require('./HoldTransfer/transferPolicy'),
  holdCommandBuilder: require('./HoldTransfer/holdCommandBuilder'),
  transferCommandBuilder: require('./HoldTransfer/transferCommandBuilder'),
  recordingManager: require('./Recording/recordingManager'),
  recordingPolicy: require('./Recording/recordingPolicy'),
  recordingCommandBuilder: require('./Recording/recordingCommandBuilder'),
  voicemailManager: require('./Voicemail/voicemailManager'),
  voicemailPolicy: require('./Voicemail/voicemailPolicy'),
  voicemailCommandBuilder: require('./Voicemail/voicemailCommandBuilder'),
  conferenceManager: require('./Conference/conferenceManager'),
  conferenceParticipantManager: require('./Conference/conferenceParticipantManager'),
  conferencePolicy: require('./Conference/conferencePolicy'),
  conferenceCommandBuilder: require('./Conference/conferenceCommandBuilder'),
  conferenceState: require('./Conference/conferenceState'),
  queueManager: require('./Queue/queueManager'),
  queueAgentManager: require('./Queue/queueAgentManager'),
  queuePolicy: require('./Queue/queuePolicy'),
  queueCommandBuilder: require('./Queue/queueCommandBuilder'),
  queueStrategy: require('./Queue/queueStrategy'),
  queueState: require('./Queue/queueState'),
  ivrManager: require('./IVR/ivrManager'),
  ivrPolicy: require('./IVR/ivrPolicy'),
  ivrMenuResolver: require('./IVR/ivrMenuResolver'),
  ivrCommandBuilder: require('./IVR/ivrCommandBuilder'),
  ivrInputProcessor: require('./IVR/ivrInputProcessor'),
  ivrState: require('./IVR/ivrState'),
  tenantBootstrap: require('./Utils/tenantBootstrap'),
  routeSnapshotHelper: require('./Utils/routeSnapshotHelper'),
  sidecarCoordinator: require('./Sidecar/sidecarCoordinator'),
  sessionCleanup: require('./Sidecar/sessionCleanup'),
  replayService: require('./Replay/replayService'),
  outboxRetention: require('./Maintenance/outboxRetention'),
};
