const PENDING_MESSAGE_STATUSES = new Set(['QUEUED', 'SENDING', 'SENT']);

const TELNYX_STATUS_TO_CHANNEL = {
  queued: 'QUEUED',
  sending: 'SENDING',
  sent: 'SENT',
  delivered: 'DELIVERED',
  failed: 'FAILED',
  received: 'RECEIVED',
  delivery_failed: 'FAILED',
  sending_failed: 'FAILED',
};

const MAX_SMS_LENGTH = 1600;
const MAX_MMS_ATTACHMENTS = 10;
const MAX_ATTACHMENT_BYTES = 5 * 1024 * 1024;
const TELNYX_SEND_MAX_RETRIES = 3;
const TELNYX_SEND_RETRY_MS = 500;
const INBOUND_MEDIA_DOWNLOAD_MAX_RETRIES = 3;
const INBOUND_MEDIA_DOWNLOAD_RETRY_MS = 500;

module.exports = {
  PENDING_MESSAGE_STATUSES,
  TELNYX_STATUS_TO_CHANNEL,
  MAX_SMS_LENGTH,
  MAX_MMS_ATTACHMENTS,
  MAX_ATTACHMENT_BYTES,
  TELNYX_SEND_MAX_RETRIES,
  TELNYX_SEND_RETRY_MS,
  INBOUND_MEDIA_DOWNLOAD_MAX_RETRIES,
  INBOUND_MEDIA_DOWNLOAD_RETRY_MS,
};
