/** Call Queue shared constants (Phase 3.8). */

const QUEUE_ACTION = {
  CREATE: 'CREATE',
  JOIN: 'JOIN',
  LEAVE: 'LEAVE',
  ASSIGN: 'ASSIGN',
  TIMEOUT: 'TIMEOUT',
  RETRY: 'RETRY',
  OVERFLOW: 'OVERFLOW',
  CLEANUP: 'CLEANUP',
  START_RECORDING: 'START_RECORDING',
  STOP_RECORDING: 'STOP_RECORDING',
  AGENT_ANSWERED: 'AGENT_ANSWERED',
};

const QUEUE_STATUS = {
  OPEN: 'OPEN',
  WAITING: 'WAITING',
  RINGING: 'RINGING',
  CONNECTED: 'CONNECTED',
  OVERFLOW: 'OVERFLOW',
  CLOSED: 'CLOSED',
  FAILED: 'FAILED',
};

const QUEUE_ENTRY_SOURCE = {
  PSTN: 'PSTN',
  DESK_TRANSFER: 'DESK_TRANSFER',
  MOBILE_TRANSFER: 'MOBILE_TRANSFER',
  DIRECT: 'DIRECT',
};

const RING_STRATEGY = {
  ROUND_ROBIN: 'ROUND_ROBIN',
  LEAST_RECENT: 'LEAST_RECENT',
  RANDOM: 'RANDOM',
  SIMULTANEOUS: 'SIMULTANEOUS',
  SEQUENTIAL: 'SEQUENTIAL',
  LONGEST_IDLE: 'LONGEST_IDLE',
};

const POLICY_ACTION = {
  ALLOW: 'ALLOW',
  DENY: 'DENY',
};

const DEFAULT_LIMITS = {
  maxWaitingTimeSec: 300,
  maxRetries: 3,
  agentTimeoutSec: 25,
  maxQueueSize: 50,
};

module.exports = {
  QUEUE_ACTION,
  QUEUE_STATUS,
  QUEUE_ENTRY_SOURCE,
  RING_STRATEGY,
  POLICY_ACTION,
  DEFAULT_LIMITS,
};
