/** IVR shared constants (Phase 3.9). */

const IVR_ACTION = {
  START: 'START',
  INPUT: 'INPUT',
  TIMEOUT: 'TIMEOUT',
  RETRY: 'RETRY',
  ROUTE: 'ROUTE',
  REPEAT: 'REPEAT',
  EXIT: 'EXIT',
};

const IVR_STATUS = {
  ACTIVE: 'ACTIVE',
  GATHERING: 'GATHERING',
  ROUTING: 'ROUTING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

const DESTINATION_TYPE = {
  EXTENSION: 'EXTENSION',
  QUEUE: 'QUEUE',
  RING_GROUP: 'RING_GROUP',
  CONFERENCE: 'CONFERENCE',
  VOICEMAIL: 'VOICEMAIL',
  OPERATOR: 'OPERATOR',
  DISCONNECT: 'DISCONNECT',
  REPEAT: 'REPEAT',
  SUBMENU: 'SUBMENU',
};

const INPUT_TYPE = {
  SINGLE: 'SINGLE',
  MULTI: 'MULTI',
  HASH: 'HASH',
  STAR: 'STAR',
  TIMEOUT: 'TIMEOUT',
  INVALID: 'INVALID',
  REPEAT: 'REPEAT',
  ESCAPE: 'ESCAPE',
};

const POLICY_ACTION = {
  ALLOW: 'ALLOW',
  DENY: 'DENY',
};

const DEFAULT_LIMITS = {
  maxRetries: 3,
  digitTimeoutSec: 5,
  interDigitTimeoutSec: 3,
  maxDigits: 10,
};

module.exports = {
  IVR_ACTION,
  IVR_STATUS,
  DESTINATION_TYPE,
  INPUT_TYPE,
  POLICY_ACTION,
  DEFAULT_LIMITS,
};
