/** Recording shared constants (Phase 3.6). */

const RECORDING_MODE = {
  MANUAL: 'MANUAL',
  AUTOMATIC: 'AUTOMATIC',
};

const RECORDING_ACTION = {
  START: 'START',
  STOP: 'STOP',
};

const POLICY_ACTION = {
  ALLOW: 'ALLOW',
  DENY: 'DENY',
};

const RECORDING_ELIGIBLE_LEG_STATES = new Set(['BRIDGED', 'ANSWERED']);

const RECORDING_ELIGIBLE_SESSION_STATES = new Set(['ACTIVE', 'HELD', 'TRANSFER_PENDING']);

const DEFAULT_LIMITS = {
  maxRecordingRetries: 2,
  retentionDays: 90,
};

module.exports = {
  RECORDING_MODE,
  RECORDING_ACTION,
  POLICY_ACTION,
  RECORDING_ELIGIBLE_LEG_STATES,
  RECORDING_ELIGIBLE_SESSION_STATES,
  DEFAULT_LIMITS,
};
